// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_compare_password_in_UserAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_compare_password_in_UserAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201810020918248_added_compare_password_in_UserAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
