// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_isdelete_in_City : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_isdelete_in_City));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121520459_Added_isdelete_in_City"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
