// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_isdelete_in_examType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_isdelete_in_examType));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121035554_added_isdelete_in_examType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
